from ntpath import join
from os import path
from reactions import (Character, atrocity_no, atrocity_yes, boring, distasteful, confusion, badass, house_burning, icup_how_spell, ignore_house_burn, join_washroom, movie_q_A, movie_q_B, movie_q_D, movie_q_norm_act, pseudo_washroom, understanding,
                       impressed, loves_energy, revulsion, fight, appreciate,
                       crowd_silence_effects, choke_neg, choke_pos, funny,
                       unimpressed, weights, lies, fap_confused,
                       event_remembers_B, person_is_profession, event_blind_A,
                       event_blind_B, event_blind_C, event_blind_D, slap,
                       event_remembers_C, chess, sincere_laugh, event_video_A,
                       event_video_C, lack_energy, arm_wrestle, event_robbery_A,
                       event_robbery_B, event_friend_ignore, event_fight_win,
                       crowd_silence_child_B, event_robbery_C, pathetic,
                       event_friend_buzz_neg, choke_neg_pos, abs_muscles,
                       event_robbery_D, math_question)
from constants import (OPTION_A, OPTION_B, OPTION_C, OPTION_D, NORMAL,
                       OBJECTIVE, ACTIVE, NEGATIVE)
from typing import Dict, Tuple
from random import choice
from file_init import first_names_lst, last_names_lst, personalities_dict

class NormalCharacter(Character):
    """
    Create a Normal Character, a subclass of Character

    """

    def reactions(self) -> Dict:
        react_dict = {0: {OPTION_A: confusion,
                          OPTION_B: appreciate,
                          OPTION_C: distasteful,
                          OPTION_D: confusion},
                       1: {OPTION_A: distasteful,
                           OPTION_B: distasteful,
                           OPTION_C: confusion,
                           OPTION_D: appreciate},
                       2: {OPTION_A: choke_neg,
                           OPTION_B: choke_pos,
                           OPTION_C: confusion,
                           OPTION_D: confusion},
                       3: {OPTION_A: crowd_silence_effects,
                           OPTION_B: understanding,
                           OPTION_C: distasteful,
                           OPTION_D: understanding},
                       4: {OPTION_A: distasteful,
                           OPTION_B: revulsion,
                           OPTION_C: understanding,
                           OPTION_D: confusion},
                       5: {OPTION_A: confusion,
                           OPTION_B: funny,
                           OPTION_C: understanding,
                           OPTION_D: distasteful},
                       6: {OPTION_A: fight,
                           OPTION_B: confusion,
                           OPTION_C: confusion,
                           OPTION_D: distasteful},
                       7: {OPTION_A: unimpressed,
                           OPTION_B: weights,
                           OPTION_C: unimpressed,
                           OPTION_D: understanding},
                       8: {OPTION_A: distasteful,
                           OPTION_B: understanding,
                           OPTION_C: distasteful,
                           OPTION_D: fap_confused},
                       9: {OPTION_A: fight,
                           OPTION_B: distasteful,
                           OPTION_C: unimpressed,
                           OPTION_D: unimpressed},
                       10: {OPTION_A: understanding,
                            OPTION_B: revulsion,
                            OPTION_C: badass,
                            OPTION_D: confusion},
                       11: {OPTION_A: event_blind_A,
                            OPTION_B: event_blind_B,
                            OPTION_C: event_blind_C,
                            OPTION_D: event_blind_D},
                       12: {OPTION_A: person_is_profession,
                            OPTION_B: understanding,
                            OPTION_C: slap,
                            OPTION_D: distasteful},
                       13: {OPTION_A: confusion,
                            OPTION_B: crowd_silence_child_B,
                            OPTION_C: crowd_silence_effects,
                            OPTION_D: appreciate},
                       14: {OPTION_A: distasteful,
                            OPTION_B: event_remembers_B,
                            OPTION_C: event_remembers_C,
                            OPTION_D: confusion},
                       15: {OPTION_A: confusion,
                            OPTION_B: confusion,
                            OPTION_C: sincere_laugh,
                            OPTION_D: abs_muscles},
                       16: {OPTION_A: event_video_A,
                            OPTION_B: appreciate,
                            OPTION_C: distasteful,
                            OPTION_D: revulsion},
                       17: {OPTION_A: event_robbery_A,
                            OPTION_B: event_robbery_B,
                            OPTION_C: event_robbery_C,
                            OPTION_D: event_robbery_D},
                       18: {OPTION_A: appreciate,
                            OPTION_B: revulsion,
                            OPTION_C: revulsion,
                            OPTION_D: revulsion},
                       19: {OPTION_A: event_friend_ignore,
                            OPTION_B: event_fight_win,
                            OPTION_C: event_friend_ignore,
                            OPTION_D: event_friend_ignore},
                       20: {OPTION_A: confusion,
                            OPTION_B: distasteful,
                            OPTION_C: appreciate,
                            OPTION_D: understanding,},
                       21: {OPTION_A: understanding,
                            OPTION_B: math_question,
                            OPTION_C: confusion,
                            OPTION_D: distasteful},
                       22: {OPTION_A: join_washroom,
                            OPTION_B: appreciate,
                            OPTION_C: distasteful,
                            OPTION_D: pseudo_washroom},
                       23: {OPTION_A: house_burning,
                            OPTION_B: ignore_house_burn,
                            OPTION_C: understanding,
                            OPTION_D: understanding},
                       24: {OPTION_A: atrocity_yes,
                            OPTION_B: atrocity_no,
                            OPTION_C: distasteful,
                            OPTION_D: understanding},
                       25: {OPTION_A: distasteful,
                            OPTION_B: funny,
                            OPTION_C: icup_how_spell,
                            OPTION_D: boring},
                       26: {OPTION_A: sincere_laugh,
                            OPTION_B: appreciate,
                            OPTION_C: distasteful,
                            OPTION_D: confusion},
                       27: {OPTION_A: distasteful,
                            OPTION_B: slap,
                            OPTION_C: understanding,
                            OPTION_D: lies},
                       28: {OPTION_A: movie_q_norm_act,
                            OPTION_B: movie_q_norm_act,
                            OPTION_C: movie_q_norm_act,
                            OPTION_D: movie_q_norm_act},
                       29: {OPTION_A: '',
                            OPTION_B: '',
                            OPTION_C: '',
                            OPTION_D: ''},
                       30: {OPTION_A: revulsion,
                            OPTION_B: understanding,
                            OPTION_C: appreciate,
                            OPTION_D: confusion},
                       31: {OPTION_A: '',
                            OPTION_B: '',
                            OPTION_C: '',
                            OPTION_D: ''},
                       32: {OPTION_A: '',
                            OPTION_B: '',
                            OPTION_C: '',
                            OPTION_D: ''},
                       33: {OPTION_A: '',
                            OPTION_B: '',
                            OPTION_C: '',
                            OPTION_D: ''},
                       34: {OPTION_A: '',
                            OPTION_B: '',
                            OPTION_C: '',
                            OPTION_D: ''},
                       35: {OPTION_A: '',
                            OPTION_B: '',
                            OPTION_C: '',
                            OPTION_D: ''},
                       36: {OPTION_A: '',
                            OPTION_B: '',
                            OPTION_C: '',
                            OPTION_D: ''},
                       37: {OPTION_A: '',
                            OPTION_B: '',
                            OPTION_C: '',
                            OPTION_D: ''},
                       38: {OPTION_A: '',
                            OPTION_B: '',
                            OPTION_C: '',
                            OPTION_D: ''},
                       39: {OPTION_A: '',
                            OPTION_B: '',
                            OPTION_C: '',
                            OPTION_D: ''},
                       40: {OPTION_A: '',
                            OPTION_B: '',
                            OPTION_C: '',
                            OPTION_D: ''},
                       41: {OPTION_A: '',
                            OPTION_B: '',
                            OPTION_C: '',
                            OPTION_D: ''},
                       42: {OPTION_A: '',
                            OPTION_B: '',
                            OPTION_C: '',
                            OPTION_D: ''},
                       43: {OPTION_A: '',
                            OPTION_B: '',
                            OPTION_C: '',
                            OPTION_D: ''},
                       44: {OPTION_A: '',
                            OPTION_B: '',
                            OPTION_C: '',
                            OPTION_D: ''},
                       45: {OPTION_A: '',
                            OPTION_B: '',
                            OPTION_C: '',
                            OPTION_D: ''},
                       46: {OPTION_A: '',
                            OPTION_B: '',
                            OPTION_C: '',
                            OPTION_D: ''},
                       47: {OPTION_A: '',
                            OPTION_B: '',
                            OPTION_C: '',
                            OPTION_D: ''},
                       48: {OPTION_A: '',
                            OPTION_B: '',
                            OPTION_C: '',
                            OPTION_D: ''},
                       49: {OPTION_A: '',
                            OPTION_B: '',
                            OPTION_C: '',
                            OPTION_D: ''},
                       50: {OPTION_A: '',
                            OPTION_B: '',
                            OPTION_C: '',
                            OPTION_D: ''}}   
        return react_dict

class ActiveCharacter(Character):
    """ 
    Create an Active Character, a subclass of Character

    """

    def reactions(self) -> Dict:
        react_dict = {0: {OPTION_A: badass,
                          OPTION_B: distasteful,
                          OPTION_C: badass,
                          OPTION_D: confusion},
                       1: {OPTION_A: distasteful,
                           OPTION_B: distasteful,
                           OPTION_C: badass,
                           OPTION_D: impressed},
                       2: {OPTION_A: choke_neg,
                           OPTION_B: choke_pos,
                           OPTION_C: loves_energy,
                           OPTION_D: confusion},
                       3: {OPTION_A: crowd_silence_effects,
                           OPTION_B: impressed,
                           OPTION_C: distasteful,
                           OPTION_D: understanding},
                       4: {OPTION_A: distasteful,
                           OPTION_B: loves_energy,
                           OPTION_C: appreciate,
                           OPTION_D: confusion},
                       5: {OPTION_A: distasteful,
                           OPTION_B: sincere_laugh,
                           OPTION_C: confusion,
                           OPTION_D: loves_energy},
                       6: {OPTION_A: fight,
                           OPTION_B: loves_energy,
                           OPTION_C: impressed,
                           OPTION_D: badass},
                       7: {OPTION_A: unimpressed,
                           OPTION_B: weights,
                           OPTION_C: unimpressed,
                           OPTION_D: understanding},
                       8: {OPTION_A: badass,
                           OPTION_B: appreciate,
                           OPTION_C: loves_energy,
                           OPTION_D: fap_confused},
                       9: {OPTION_A: fight,
                           OPTION_B: distasteful,
                           OPTION_C: unimpressed,
                           OPTION_D: revulsion},
                       10: {OPTION_A: revulsion,
                            OPTION_B: loves_energy,
                            OPTION_C: badass,
                            OPTION_D: revulsion},
                       11: {OPTION_A: event_blind_A,
                            OPTION_B: event_blind_B,
                            OPTION_C: event_blind_C,
                            OPTION_D: event_blind_D},
                       12: {OPTION_A: person_is_profession,
                            OPTION_B: distasteful,
                            OPTION_C: distasteful,
                            OPTION_D: unimpressed},
                       13: {OPTION_A: confusion,
                            OPTION_B: crowd_silence_child_B,
                            OPTION_C: crowd_silence_effects,
                            OPTION_D: distasteful},
                       14: {OPTION_A: distasteful,
                            OPTION_B: event_remembers_B,
                            OPTION_C: event_remembers_C,
                            OPTION_D: confusion},
                       15: {OPTION_A: arm_wrestle,
                            OPTION_B: distasteful,
                            OPTION_C: confusion,
                            OPTION_D: abs_muscles},
                       16: {OPTION_A: event_video_A,
                            OPTION_B: lack_energy,
                            OPTION_C: event_video_C,
                            OPTION_D: revulsion},
                       17: {OPTION_A: event_robbery_A,
                            OPTION_B: event_robbery_B,
                            OPTION_C: event_robbery_C,
                            OPTION_D: event_robbery_D},
                       18: {OPTION_A: badass,
                            OPTION_B: revulsion,
                            OPTION_C: revulsion,
                            OPTION_D: revulsion},
                       19: {OPTION_A: event_friend_ignore,
                            OPTION_B: event_fight_win,
                            OPTION_C: event_friend_ignore,
                            OPTION_D: event_friend_buzz_neg},
                       20: {OPTION_A: loves_energy,
                            OPTION_B: revulsion,
                            OPTION_C: boring,
                            OPTION_D: unimpressed},
                       21: {OPTION_A: understanding,
                            OPTION_B: math_question,
                            OPTION_C: revulsion,
                            OPTION_D: understanding},
                       22: {OPTION_A: join_washroom,
                            OPTION_B: boring,
                            OPTION_C: loves_energy,
                            OPTION_D: pseudo_washroom},
                       23: {OPTION_A: house_burning,
                            OPTION_B: ignore_house_burn,
                            OPTION_C: distasteful,
                            OPTION_D: loves_energy},
                       24: {OPTION_A: atrocity_yes,
                            OPTION_B: atrocity_no,
                            OPTION_C: distasteful,
                            OPTION_D: lack_energy},
                       25: {OPTION_A: boring,
                            OPTION_B: loves_energy,
                            OPTION_C: icup_how_spell,
                            OPTION_D: distasteful},
                       26: {OPTION_A: loves_energy,
                            OPTION_B: boring,
                            OPTION_C: slap,
                            OPTION_D: confusion},
                       27: {OPTION_A: loves_energy,
                            OPTION_B: appreciate,
                            OPTION_C: boring,
                            OPTION_D: lack_energy},
                       28: {OPTION_A: movie_q_norm_act,
                            OPTION_B: movie_q_norm_act,
                            OPTION_C: movie_q_norm_act,
                            OPTION_D: movie_q_norm_act},
                       29: {OPTION_A: '',
                            OPTION_B: '',
                            OPTION_C: '',
                            OPTION_D: ''},
                       30: {OPTION_A: loves_energy,
                            OPTION_B: lack_energy,
                            OPTION_C: boring,
                            OPTION_D: loves_energy},
                       31: {OPTION_A: '',
                            OPTION_B: '',
                            OPTION_C: '',
                            OPTION_D: ''},
                       32: {OPTION_A: '',
                            OPTION_B: '',
                            OPTION_C: '',
                            OPTION_D: ''},
                       33: {OPTION_A: '',
                            OPTION_B: '',
                            OPTION_C: '',
                            OPTION_D: ''},
                       34: {OPTION_A: '',
                            OPTION_B: '',
                            OPTION_C: '',
                            OPTION_D: ''},
                       35: {OPTION_A: '',
                            OPTION_B: '',
                            OPTION_C: '',
                            OPTION_D: ''},
                       36: {OPTION_A: '',
                            OPTION_B: '',
                            OPTION_C: '',
                            OPTION_D: ''},
                       37: {OPTION_A: '',
                            OPTION_B: '',
                            OPTION_C: '',
                            OPTION_D: ''},
                       38: {OPTION_A: '',
                            OPTION_B: '',
                            OPTION_C: '',
                            OPTION_D: ''},
                       39: {OPTION_A: '',
                            OPTION_B: '',
                            OPTION_C: '',
                            OPTION_D: ''},
                       40: {OPTION_A: '',
                            OPTION_B: '',
                            OPTION_C: '',
                            OPTION_D: ''},
                       41: {OPTION_A: '',
                            OPTION_B: '',
                            OPTION_C: '',
                            OPTION_D: ''},
                       42: {OPTION_A: '',
                            OPTION_B: '',
                            OPTION_C: '',
                            OPTION_D: ''},
                       43: {OPTION_A: '',
                            OPTION_B: '',
                            OPTION_C: '',
                            OPTION_D: ''},
                       44: {OPTION_A: '',
                            OPTION_B: '',
                            OPTION_C: '',
                            OPTION_D: ''},
                       45: {OPTION_A: '',
                            OPTION_B: '',
                            OPTION_C: '',
                            OPTION_D: ''},
                       46: {OPTION_A: '',
                            OPTION_B: '',
                            OPTION_C: '',
                            OPTION_D: ''},
                       47: {OPTION_A: '',
                            OPTION_B: '',
                            OPTION_C: '',
                            OPTION_D: ''},
                       48: {OPTION_A: '',
                            OPTION_B: '',
                            OPTION_C: '',
                            OPTION_D: ''},
                       49: {OPTION_A: '',
                            OPTION_B: '',
                            OPTION_C: '',
                            OPTION_D: ''},
                       50: {OPTION_A: '',
                            OPTION_B: '',
                            OPTION_C: '',
                            OPTION_D: ''}}
        return react_dict

class NegativeCharacter(Character):
    """ 
    Create a Negative Character, a subclass of Character

    """
    
    def reactions(self) -> Dict:
        react_dict = {0: {OPTION_A: unimpressed,
                          OPTION_B: distasteful,
                          OPTION_C: appreciate,
                          OPTION_D: confusion},
                       1: {OPTION_A: confusion,
                           OPTION_B: pathetic,
                           OPTION_C: understanding,
                           OPTION_D: distasteful},
                       2: {OPTION_A: choke_neg_pos,
                           OPTION_B: choke_neg_pos,
                           OPTION_C: choke_neg_pos,
                           OPTION_D: choke_neg_pos},
                       3: {OPTION_A: crowd_silence_effects,
                           OPTION_B: understanding,
                           OPTION_C: sincere_laugh,
                           OPTION_D: distasteful},
                       4: {OPTION_A: funny,
                           OPTION_B: revulsion,
                           OPTION_C: distasteful,
                           OPTION_D: confusion},
                       5: {OPTION_A: confusion,
                           OPTION_B: distasteful,
                           OPTION_C: pathetic,
                           OPTION_D: distasteful},
                       6: {OPTION_A: fight,
                           OPTION_B: confusion,
                           OPTION_C: confusion,
                           OPTION_D: pathetic},
                       7: {OPTION_A: appreciate,
                           OPTION_B: weights,
                           OPTION_C: understanding,
                           OPTION_D: distasteful},
                       8: {OPTION_A: distasteful,
                           OPTION_B: pathetic,
                           OPTION_C: unimpressed,
                           OPTION_D: pathetic},
                       9: {OPTION_A: fight,
                           OPTION_B: funny,
                           OPTION_C: unimpressed,
                           OPTION_D: pathetic},
                       10: {OPTION_A: distasteful,
                            OPTION_B: distasteful,
                            OPTION_C: funny,
                            OPTION_D: pathetic},
                       11: {OPTION_A: event_blind_A,
                            OPTION_B: event_blind_B,
                            OPTION_C: event_blind_C,
                            OPTION_D: event_blind_D},
                       12: {OPTION_A: person_is_profession,
                            OPTION_B: pathetic,
                            OPTION_C: funny,
                            OPTION_D: unimpressed},
                       13: {OPTION_A: understanding,
                            OPTION_B: crowd_silence_child_B,
                            OPTION_C: crowd_silence_effects,
                            OPTION_D: distasteful},
                       14: {OPTION_A: funny,
                            OPTION_B: event_remembers_B,
                            OPTION_C: event_remembers_C,
                            OPTION_D: confusion},
                       15: {OPTION_A: distasteful,
                            OPTION_B: distasteful,
                            OPTION_C: distasteful,
                            OPTION_D: abs_muscles},
                       16: {OPTION_A: event_video_A,
                            OPTION_B: appreciate,
                            OPTION_C: event_video_C,
                            OPTION_D: pathetic},
                       17: {OPTION_A: event_robbery_A,
                            OPTION_B: event_robbery_B,
                            OPTION_C: event_robbery_C,
                            OPTION_D: event_robbery_D},
                       18: {OPTION_A: badass,
                            OPTION_B: revulsion,
                            OPTION_C: revulsion,
                            OPTION_D: revulsion},
                       19: {OPTION_A: event_friend_ignore,
                            OPTION_B: event_fight_win,
                            OPTION_C: event_friend_ignore,
                            OPTION_D: event_friend_buzz_neg},
                       20: {OPTION_A: sincere_laugh,
                            OPTION_B: appreciate,
                            OPTION_C: distasteful,
                            OPTION_D: pathetic},
                       21: {OPTION_A: pathetic,
                            OPTION_B: math_question,
                            OPTION_C: pathetic,
                            OPTION_D: pathetic},
                       22: {OPTION_A: join_washroom,
                            OPTION_B: unimpressed,
                            OPTION_C: funny,
                            OPTION_D: pseudo_washroom},
                       23: {OPTION_A: house_burning,
                            OPTION_B: ignore_house_burn,
                            OPTION_C: distasteful,
                            OPTION_D: unimpressed},
                       24: {OPTION_A: atrocity_yes,
                            OPTION_B: atrocity_no,
                            OPTION_C: pathetic,
                            OPTION_D: funny},
                       25: {OPTION_A: distasteful,
                            OPTION_B: pathetic,
                            OPTION_C: pathetic,
                            OPTION_D: funny},
                       26: {OPTION_A: pathetic,
                            OPTION_B: boring,
                            OPTION_C: appreciate,
                            OPTION_D: sincere_laugh},
                       27: {OPTION_A: pathetic,
                            OPTION_B: funny,
                            OPTION_C: pathetic,
                            OPTION_D: lies},
                       28: {OPTION_A: movie_q_A,
                            OPTION_B: movie_q_B,
                            OPTION_C: impressed,
                            OPTION_D: movie_q_D},
                       29: {OPTION_A: '',
                            OPTION_B: '',
                            OPTION_C: '',
                            OPTION_D: ''},
                       30: {OPTION_A: appreciate,
                            OPTION_B: appreciate,
                            OPTION_C: distasteful,
                            OPTION_D: understanding},
                       31: {OPTION_A: '',
                            OPTION_B: '',
                            OPTION_C: '',
                            OPTION_D: ''},
                       32: {OPTION_A: '',
                            OPTION_B: '',
                            OPTION_C: '',
                            OPTION_D: ''},
                       33: {OPTION_A: '',
                            OPTION_B: '',
                            OPTION_C: '',
                            OPTION_D: ''},
                       34: {OPTION_A: '',
                            OPTION_B: '',
                            OPTION_C: '',
                            OPTION_D: ''},
                       35: {OPTION_A: '',
                            OPTION_B: '',
                            OPTION_C: '',
                            OPTION_D: ''},
                       36: {OPTION_A: '',
                            OPTION_B: '',
                            OPTION_C: '',
                            OPTION_D: ''},
                       37: {OPTION_A: '',
                            OPTION_B: '',
                            OPTION_C: '',
                            OPTION_D: ''},
                       38: {OPTION_A: '',
                            OPTION_B: '',
                            OPTION_C: '',
                            OPTION_D: ''},
                       39: {OPTION_A: '',
                            OPTION_B: '',
                            OPTION_C: '',
                            OPTION_D: ''},
                       40: {OPTION_A: '',
                            OPTION_B: '',
                            OPTION_C: '',
                            OPTION_D: ''},
                       41: {OPTION_A: '',
                            OPTION_B: '',
                            OPTION_C: '',
                            OPTION_D: ''},
                       42: {OPTION_A: '',
                            OPTION_B: '',
                            OPTION_C: '',
                            OPTION_D: ''},
                       43: {OPTION_A: '',
                            OPTION_B: '',
                            OPTION_C: '',
                            OPTION_D: ''},
                       44: {OPTION_A: '',
                            OPTION_B: '',
                            OPTION_C: '',
                            OPTION_D: ''},
                       45: {OPTION_A: '',
                            OPTION_B: '',
                            OPTION_C: '',
                            OPTION_D: ''},
                       46: {OPTION_A: '',
                            OPTION_B: '',
                            OPTION_C: '',
                            OPTION_D: ''},
                       47: {OPTION_A: '',
                            OPTION_B: '',
                            OPTION_C: '',
                            OPTION_D: ''},
                       48: {OPTION_A: '',
                            OPTION_B: '',
                            OPTION_C: '',
                            OPTION_D: ''},
                       49: {OPTION_A: '',
                            OPTION_B: '',
                            OPTION_C: '',
                            OPTION_D: ''},
                       50: {OPTION_A: '',
                            OPTION_B: '',
                            OPTION_C: '',
                            OPTION_D: ''}}
        return react_dict

class ObjectiveCharacter(Character):
    """ 
    Create an Objective Character, a subclass of Character

    """

    def reactions(self) -> Dict:
        react_dict = {0: {OPTION_A: confusion,
                          OPTION_B: understanding,
                          OPTION_C: confusion,
                          OPTION_D: confusion},
                       1: {OPTION_A: impressed,
                           OPTION_B: understanding,
                           OPTION_C: distasteful,
                           OPTION_D: understanding},
                       2: {OPTION_A: choke_neg,
                           OPTION_B: choke_pos,
                           OPTION_C: confusion,
                           OPTION_D: confusion},
                       3: {OPTION_A: crowd_silence_effects,
                           OPTION_B: understanding,
                           OPTION_C: distasteful,
                           OPTION_D: unimpressed},
                       4: {OPTION_A: distasteful,
                           OPTION_B: revulsion,
                           OPTION_C: appreciate,
                           OPTION_D: funny},
                       5: {OPTION_A: distasteful,
                           OPTION_B: distasteful,
                           OPTION_C: confusion,
                           OPTION_D: distasteful},
                       6: {OPTION_A: fight,
                           OPTION_B: confusion,
                           OPTION_C: confusion,
                           OPTION_D: confusion},
                       7: {OPTION_A: sincere_laugh,
                           OPTION_B: weights,
                           OPTION_C: funny,
                           OPTION_D: impressed},
                       8: {OPTION_A: sincere_laugh,
                           OPTION_B: unimpressed,
                           OPTION_C: revulsion,
                           OPTION_D: revulsion},
                       9: {OPTION_A: fight,
                           OPTION_B: unimpressed,
                           OPTION_C: distasteful,
                           OPTION_D: revulsion},
                       10: {OPTION_A: sincere_laugh,
                            OPTION_B: funny,
                            OPTION_C: lies,
                            OPTION_D: unimpressed},
                       11: {OPTION_A: event_blind_A,
                            OPTION_B: event_blind_B,
                            OPTION_C: event_blind_C,
                            OPTION_D: event_blind_D},
                       12: {OPTION_A: person_is_profession,
                            OPTION_B: unimpressed,
                            OPTION_C: distasteful,
                            OPTION_D: sincere_laugh},
                       13: {OPTION_A: confusion,
                            OPTION_B: crowd_silence_child_B,
                            OPTION_C: crowd_silence_effects,
                            OPTION_D: appreciate},
                       14: {OPTION_A: revulsion,
                            OPTION_B: event_remembers_B,
                            OPTION_C: event_remembers_C,
                            OPTION_D: confusion},
                       15: {OPTION_A: confusion,
                            OPTION_B: chess,
                            OPTION_C: impressed,
                            OPTION_D: abs_muscles},
                       16: {OPTION_A: event_video_A,
                            OPTION_B: impressed,
                            OPTION_C: distasteful,
                            OPTION_D: revulsion},
                       17: {OPTION_A: event_robbery_A,
                            OPTION_B: event_robbery_B,
                            OPTION_C: event_robbery_C,
                            OPTION_D: event_robbery_D},
                       18: {OPTION_A: appreciate,
                            OPTION_B: revulsion,
                            OPTION_C: revulsion,
                            OPTION_D: revulsion},
                       19: {OPTION_A: event_friend_ignore,
                            OPTION_B: event_fight_win,
                            OPTION_C: event_friend_ignore,
                            OPTION_D: event_friend_ignore},
                       20: {OPTION_A: sincere_laugh,
                            OPTION_B: distasteful,
                            OPTION_C: appreciate,
                            OPTION_D: confusion},
                       21: {OPTION_A: sincere_laugh,
                            OPTION_B: math_question,
                            OPTION_C: appreciate,
                            OPTION_D: revulsion},
                       22: {OPTION_A: join_washroom,
                            OPTION_B: appreciate,
                            OPTION_C: confusion,
                            OPTION_D: pseudo_washroom},
                       23: {OPTION_A: house_burning,
                            OPTION_B: ignore_house_burn,
                            OPTION_C: distasteful,
                            OPTION_D: unimpressed},
                       24: {OPTION_A: atrocity_yes,
                            OPTION_B: atrocity_no,
                            OPTION_C: unimpressed,
                            OPTION_D: unimpressed},
                       25: {OPTION_A: sincere_laugh,
                            OPTION_B: distasteful,
                            OPTION_C: icup_how_spell,
                            OPTION_D: appreciate},
                       26: {OPTION_A: distasteful,
                            OPTION_B: appreciate,
                            OPTION_C: unimpressed,
                            OPTION_D: sincere_laugh},
                       27: {OPTION_A: funny,
                            OPTION_B: impressed,
                            OPTION_C: sincere_laugh,
                            OPTION_D: lies},
                       28: {OPTION_A: movie_q_A,
                            OPTION_B: movie_q_B,
                            OPTION_C: impressed,
                            OPTION_D: movie_q_D},
                       29: {OPTION_A: '',
                            OPTION_B: '',
                            OPTION_C: '',
                            OPTION_D: ''},
                       30: {OPTION_A: impressed,
                            OPTION_B: understanding,
                            OPTION_C: distasteful,
                            OPTION_D: confusion},
                       31: {OPTION_A: '',
                            OPTION_B: '',
                            OPTION_C: '',
                            OPTION_D: ''},
                       32: {OPTION_A: '',
                            OPTION_B: '',
                            OPTION_C: '',
                            OPTION_D: ''},
                       33: {OPTION_A: '',
                            OPTION_B: '',
                            OPTION_C: '',
                            OPTION_D: ''},
                       34: {OPTION_A: '',
                            OPTION_B: '',
                            OPTION_C: '',
                            OPTION_D: ''},
                       35: {OPTION_A: '',
                            OPTION_B: '',
                            OPTION_C: '',
                            OPTION_D: ''},
                       36: {OPTION_A: '',
                            OPTION_B: '',
                            OPTION_C: '',
                            OPTION_D: ''},
                       37: {OPTION_A: '',
                            OPTION_B: '',
                            OPTION_C: '',
                            OPTION_D: ''},
                       38: {OPTION_A: '',
                            OPTION_B: '',
                            OPTION_C: '',
                            OPTION_D: ''},
                       39: {OPTION_A: '',
                            OPTION_B: '',
                            OPTION_C: '',
                            OPTION_D: ''},
                       40: {OPTION_A: '',
                            OPTION_B: '',
                            OPTION_C: '',
                            OPTION_D: ''},
                       41: {OPTION_A: '',
                            OPTION_B: '',
                            OPTION_C: '',
                            OPTION_D: ''},
                       42: {OPTION_A: '',
                            OPTION_B: '',
                            OPTION_C: '',
                            OPTION_D: ''},
                       43: {OPTION_A: '',
                            OPTION_B: '',
                            OPTION_C: '',
                            OPTION_D: ''},
                       44: {OPTION_A: '',
                            OPTION_B: '',
                            OPTION_C: '',
                            OPTION_D: ''},
                       45: {OPTION_A: '',
                            OPTION_B: '',
                            OPTION_C: '',
                            OPTION_D: ''},
                       46: {OPTION_A: '',
                            OPTION_B: '',
                            OPTION_C: '',
                            OPTION_D: ''},
                       47: {OPTION_A: '',
                            OPTION_B: '',
                            OPTION_C: '',
                            OPTION_D: ''},
                       48: {OPTION_A: '',
                            OPTION_B: '',
                            OPTION_C: '',
                            OPTION_D: ''},
                       49: {OPTION_A: '',
                            OPTION_B: '',
                            OPTION_C: '',
                            OPTION_D: ''},
                       50: {OPTION_A: '',
                            OPTION_B: '',
                            OPTION_C: '',
                            OPTION_D: ''}}
        return react_dict


def person_creator() -> Character:
    """ 
    Return a unique subclass of the Character class.

    This includes creating the Character's true_pers, pers, name, first_name,
    last_name, and prof.

    """

    behaviour, profile = '', ''
    character_dict = {NORMAL: NormalCharacter,
                      NEGATIVE: NegativeCharacter,
                      ACTIVE: ActiveCharacter,
                      OBJECTIVE: ObjectiveCharacter}
    behaviour = rand_pers()
    profile = character_dict.get(behaviour[0])(rand_nam(), behaviour[0],
                                               behaviour[1])
    return profile

def rand_nam() -> str:
    """
    Create a random name to 'battle.'
    This involves grabbing a random first and last name
    from 'women_first_names.txt' and 'last_names.txt' respectively.

    """
    return choice(first_names_lst()) + ' ' + choice(last_names_lst())


def rand_pers() -> Tuple[str, str]:
    """
    Assign a random personality to a character.

    Personalities fall into one of four categories:

    - Active
    - Objective
    - Negative
    - Normal

    To spice things up a bit, each category has a list of synomnyms that
    belong to it. Return the category and the synonym as a tuple.

    """
    personalities = personalities_dict()
    key = choice(list(personalities.keys()))
    value = choice(personalities.get(key))
    return key, value
